/*
 * ACTIONS
 */

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESFUL"
export const LOGOUT = "LOGOUT";

export const FETCH_PROFILE = "FETCH_PROFILE";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_ERROR = "FETCH_PROFILE_ERROR";
export const FETCH_PROFILE_FAILURE = "FETCH_PROFILE_FAILURE";

export const FETCH_EVENTS = "FETCH_EVENTS";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_ERROR = "FETCH_EVENTS_ERROR";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";

export const FETCH_EVENT = "FETCH_EVENT";
export const FETCH_EVENT_SUCCESS = "FETCH_EVENT_SUCCESS";
export const FETCH_EVENT_ERROR = "FETCH_EVENT_ERROR";
export const FETCH_EVENT_FAILURE = "FETCH_EVENT_FAILURE";


export const POST_EVENT = "POST_EVENT";
export const POST_EVENT_SUCCESS = "POST_EVENT_SUCCESS";
export const POST_EVENT_ERROR = "POST_EVENT_ERROR";
export const POST_EVENT_FAILURE = "POST_EVENT_FAILURE";

export const POST_PARTICIPANT = "POST_PARTICIPANT";
export const POST_PARTICIPANT_SUCCESS = "POST_PARTICIPANT_SUCCESS";
export const POST_PARTICIPANT_ERROR = "POST_PARTICIPANT_ERROR";
export const POST_PARTICIPANT_FAILURE = "POST_PARTICIPANT_FAILURE";

export const UI_JOIN_SUCCESS_ALERT = "UI_JOIN_SUCCESS_ALERT";
export const UI_JOIN_ERROR_ALERT = "UI_JOIN_ERROR_ALERT";
export const UI_JOIN_SUCCESS_ALERT_HIDE = "UI_JOIN_SUCCESS_ALERT_HIDE";
export const UI_JOIN_ERROR_ALERT_HIDE = "UI_JOIN_ERROR_ALERT_HIDE";


export const UI_CREATE_SUCCESS_ALERT = "UI_CREATE_SUCCESS_ALERT";
export const UI_CREATE_ERROR_ALERT = "UI_CREATE_ERROR_ALERT";
export const UI_CREATE_SUCCESS_ALERT_HIDE = "UI_CREATE_SUCCESS_ALERT_HIDE";
export const UI_CREATE_ERROR_ALERT_HIDE = "UI_CREATE_ERROR_ALERT_HIDE";

