export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const FETCH_PROFILE = "FETCH_PROFILE";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE";
export const FETCH_PROFILE_ERROR = "FETCH_PROFILE_ERROR";
export const FETCH_PROFILE_FAILURE = "FETCH_PROFILE_FAILURE";