# Generated by Django 3.0.4 on 2020-03-29 20:08

import api.models
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('picture', models.ImageField(default='default-profile.jpg', upload_to='profile_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('tette', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('address', models.CharField(max_length=100)),
                ('destination', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(44.629418, 10.948245), srid=4326)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, validators=[api.models.validate_date_not_in_past])),
                ('status', models.SmallIntegerField(choices=[(1, 'Joinable'), (2, 'Computing'), (3, 'Computed')], default=1)),
                ('picture', models.ImageField(default='default-event.jpg', upload_to='event_pictures')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
            options={
                'unique_together': {('date_time', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tot_avail_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(9)])),
                ('consumption', models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fuel', models.SmallIntegerField(choices=[(1, 'Petrol'), (2, 'Diesel'), (3, 'Gas'), (4, 'Electric')], default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_address', models.CharField(blank=True, max_length=100)),
                ('starting_pos', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('pickup_index', models.SmallIntegerField(default=-1)),
                ('expense', models.FloatField(default=-1)),
                ('is_driver', models.BooleanField(default=False)),
                ('car', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Car')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
            options={
                'unique_together': {('profile', 'event')},
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='', max_length=500)),
                ('vote', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Event')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gived_feedback', to='api.Profile')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to='api.Profile')),
            ],
            options={
                'unique_together': {('giver', 'receiver', 'event')},
            },
        ),
    ]
