# Generated by Django 3.0.4 on 2020-03-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Joinable'), (1, 'Computing'), (2, 'Computed')], default=1),
        ),
    ]
