# Generated by Django 3.0.4 on 2020-03-30 21:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200330_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='destination',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Joinable'), (1, 'Computing'), (2, 'Computed')], default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='starting_pos',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
