# Generated by Django 3.0.4 on 2020-03-31 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200330_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to='api.Profile'),
        ),
    ]
