# Generated by Django 3.0.4 on 2020-04-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to='profile_pictures'),
        ),
    ]
