# Generated by Django 3.0.5 on 2020-05-08 11:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200412_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='destination',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='starting_pos',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
