# Generated by Django 3.0.5 on 2020-07-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200508_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.Event'),
            preserve_default=False,
        ),
    ]
