/*
    Auth
*/
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";


/*
    Profile
 */
export const PROFILE_OP_START = "PROFILE_OP_START";
export const PROFILE_OP_ERROR = "PROFILE_OP_ERROR";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const CLEAR_PROFILE_DATA = "CLEAR_PROFILE_DATA";

/*
    Profile - Car
 */
export const CAR_CREATE = "CAR_CREATE";
export const CAR_UPDATE = "CAR_UPDATE";
export const CAR_DELETE = "CAR_DELETE";

/*
    Notifications
 */
export const NOTIFICATIONS_START = "NOTIFICATIONS_START";
export const NOTIFICATIONS_ERROR = "NOTIFICATIONS_ERROR";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const NOTIFICATION_UPDATE = "NOTIFICATION_UPDATE";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";