# Generated by Django 3.0.3 on 2020-02-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedDrivers', '0003_auto_20200229_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('date_time', 'destination')},
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'event')},
        ),
    ]
