# Generated by Django 3.0.3 on 2020-03-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedDrivers', '0004_auto_20200229_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
