# Generated by Django 3.0.3 on 2020-03-02 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharedDrivers', '0005_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='score',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='participant',
            name='starting_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='car',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='SharedDrivers.Car'),
        ),
    ]
