# Generated by Django 3.0.3 on 2020-03-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SharedDrivers', '0006_auto_20200302_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='score',
        ),
    ]
