# Generated by Django 3.0.3 on 2020-03-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedDrivers', '0007_remove_participant_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Joinable'), (2, 'Computing'), (3, 'Computed')], default=1),
        ),
    ]
