# Generated by Django 3.0.4 on 2020-03-11 12:47

import SharedDrivers.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SharedDrivers', '0009_auto_20200306_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='consumption',
            field=models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[SharedDrivers.models.validate_date_not_in_past]),
        ),
    ]
